### ISSUE TITLE
How can run docker command in .gitlab-ci.yml

### ISSUE THREAD

**Issue by qq253498229** [lwolf/helm-kubectl-docker#6]
I want to login my registry and pull images,and then run helm/kubectl .
But I found lwolf/helm-kubectl-docker could not run docker command.How can I resolve it?
Can you please give me some advice?

**Comment by lwolf** [comment]
This container is not supposed to run docker containers, but to execute helm/kubectl commands. You should restructure your gitlab-ci pipeline to use this container in the deployment step.
here is the old [blog-post](https://blog.lwolf.org/post/how-to-create-ci-cd-pipeline-with-autodeploy-k8s-gitlab-helm/) describing the usage of the similar approach.

**Comment by qq253498229** [comment]
thank you very much
